source/project/dungeons_and_devs/core/views.py
#core/views.py
from flask import render_template,request,Blueprint
from dungeons_and_devs.models import Character
core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    characters = Character.query.order_by(Character.name.asc()).paginate(page=page, per_page=5)

    return render_template('index.html',characters=characters)

@core.route('/info')
def info():
    return render_template('info.html')

source/project/dungeons_and_devs/posts/views.py
#posts/views.py
#creating updating and deleting character views
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import current_user,login_required
from dungeons_and_devs import db
from dungeons_and_devs.models import Character
from dungeons_and_devs.posts.forms import CreateCharacterForm

characters = Blueprint('characters',__name__)
######################CRUDCRUDCRUDCRUDCRUD######################################
###CREATING A CHARACTER VIEW
@characters.route('/create',methods=['GET','POST'])
@login_required
def create_character():
    form = CreateCharacterForm()

    if form.validate_on_submit():

        character = Character(name=form.name.data,
                              level=form.level.data,
                              class_=form.class_.data,
                              saves=form.saves.data,
                              race=form.race.data,
                              gender=form.gender.data,
                              age=form.age.data,
                              weight=form.weight.data,
                              hair=form.hair.data,
                              eyes=form.eyes.data,
                              notes=form.notes.data,
                              user_id=current_user.id)
        db.session.add(character)
        db.session.commit()
        flash('Character Created')
        return redirect(url_for('core.index'))

    return render_template('create_character.html',form=form)

###VIEWING A CHARACTER
@characters.route('/<int:character_id>')
def character(character_id):
    character = Character.query.get_or_404(character_id)
    return render_template('character.html',name=character.name,
                                           level=character.level,
                                           class_=character.class_,
                                           saves=character.saves,
                                           race=character.race,
                                           gender=character.gender,
                                           age=character.age,
                                           weight=character.weight,
                                           hair=character.hair,
                                           eyes=character.eyes,
                                           notes=character.notes)

###UPDATING A CHARACTER
@characters.route('/<int:character_id>/update',methods=['GET','POST'])
@login_required
def update(character_id):
    character = Character.query.get_or_404(character_id)

    if character.owner != current_user:
        abort(403)

    form = CreateCharacterForm()
    if form.validate_on_submit():

        character.name=form.name.data
        character.level=form.level.data
        character.class_=form.class_.data
        character.saves=form.saves.data
        character.race=form.race.data
        character.gender=form.gender.data
        character.age=form.age.data
        character.weight=form.weight.data
        character.hair=form.hair.data
        character.eyes=form.eyes.data
        character.notes=form.notes.data

        db.session.commit()
        flash('Character Updated')
        return redirect(url_for('characters.character', character_id=character.id))

    elif request.method == 'GET':
        form.name.data = character.name
        form.level.data = character.level
        form.class_.data = character.class_
        form.saves.data = character.saves
        form.race.data = character.race
        form.gender.data = character.gender
        form.age.data = character.age
        form.weight.data = character.weight
        form.hair.data = character.hair
        form.eyes.data = character.eyes
        form.notes.data = character.notes



    return render_template('create_character.html',form=form)


###DELETING A CHARACTER
@characters.route('/<int:character_id>/delete',methods=['GET','POST'])
@login_required
def delete_charcter(character):
    character = Character.query.get_or_404(character_id)

    if character.owner != current_user:
        abort(403)

    db.session.delete(character)
    db.session.commit()
    flash('Character Successfully Deleted')
    return redirect(url_for('core.index'))

source/project/dungeons_and_devs/users/views.py
#users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from dungeons_and_devs import db#THIS is in __init__ sql alchemy object
from dungeons_and_devs.models import User,Character #,Compendium
from dungeons_and_devs.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from dungeons_and_devs.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

#VIEWS WE WANT TO see
#register
@users.route("/register",methods=['GET','POST'])
def register():
    form = RegistrationForm()
    #creates a valid user object
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Successfully Registered')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)


#login
@users.route("/login",methods=['GET','POST'])
def login():
    form = LoginForm()
    #validates user
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Login Success')
            #if user is trying to access a user specific pg without being logged in
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
        return render_template('login.html',form=form)
    return render_template('login.html',form=form)


#logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


#account (update userform)
@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#users character(s)####3THIS PORTION WILL DIFFER FROM B-POSTS
@users.route("/<username>")
def user_characters(username):
    page = request.args.get('page', 1, type=int) #each pg refers to 1 character(this allows users to cycle through each character individually)

    user = User.query.filter_by(username=username).first_or_404()

    characters = Character.query.filter_by(owner=user).order_by(Character.name.asc()).paginate(page=page, per_page=5)#lists characters in ascneding order by name

    return render_template('user_characters.html', characters=characters, user=user)



#entire compendium view!!! (BIG ONE)

source/project/dungeons_and_devs/templates/account.html
{% extends "base.html" %}
{% block content %}
<br>
  <div class="jumbotron font-monospace">
    <div align='center'>
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <img class="rounded-circle border border-dark border-4" align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    </div>
  </div>

  <div class="container font-monospace">
    <form method="POST" action=" " enctype="multipart/form-data">

      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>

      <div class="form-group">
        {{form.email.label(class='form-group')}}
        {{form.email(class='form-group')}}
      </div>

      <div class="form-group">
        {{form.picture.label(class='form-group')}}
        {{form.picture(class='form-group')}}
      </div>

      <div class="form-group">
        {{form.submit(class='btn btn-primary')}}
      </div>



    </form>
  </div>

{% endblock %}

source/project/dungeons_and_devs/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- 2 lines below are from bootstrap website -->
    <link rel="stylesheet" type="text/css" href="style.css" media="screen"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


    <!-- SETTING UP NAVIGATION BAR -->

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top font-monospace">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('core.index')}}">Dungeons & Devs</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item">
                <a class="nav-link" href="{{url_for('core.info')}}">About Us</a>
              </li>
              {% if current_user.is_authenticated %}
              
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.account')}}">Profile</a>
                </li>
                <li class='nav-item'>
                  <a class="nav-link" href="{{url_for('characters.create_character')}}">Create Character</a>
                </li>
                <li class='nav-item'>
                  <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
                </li>
              {% else %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Login
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{{url_for('users.login')}}">Login</a></li>
                  <li><a class="dropdown-item" href="{{url_for('users.register')}}">Register</a></li>
                </ul>
              </li>


              {% endif %}
            </ul>




          </div>
        </div>
    </nav>



    <div class="container">
      {% block content %}



      {% endblock %}
    </div>


  </body>
</html>

source/project/dungeons_and_devs/templates/character.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="jumbotron container font-monospace">

  <ul class="list-group">
  <li class="list-group-item active" aria-current="true"><h1>{{name}}</h1></li>
  <li class="list-group-item">Level: {{level}}</li>
  <li class="list-group-item">Class: {{class_}}</li>
  <li class="list-group-item">Saves: {{saves}}</li>
  <li class="list-group-item">Race: {{race}}</li>
  <li class="list-group-item">Gender: {{gender}}</li>
  <li class="list-group-item">Age: {{age}}</li>
  <li class="list-group-item">Weight: {{weight}}</li>
  <li class="list-group-item">Hair: {{hair}}</li>
  <li class="list-group-item">Eyes: {{eyes}}</li>
  <li class="list-group-item">Notes: {{notes}}</li>
  </ul>


</div>

{% endblock %}

source/project/dungeons_and_devs/templates/create_character.html
{% extends "base.html" %}
{% block content %}
<br>
  <div class="container" style="width: 50rem;" align='center'>
    <form class="form-group" method="POST">
      <div class="card font-monospace ">
        <div class="card-header">
      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.name.label(class="form-control-label")}}
        {{form.name(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.level.label(class="form-control-label")}}
        {{form.level(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.class_.label(class="form-control-label")}}
        {{form.class_(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.saves.label(class="form-control-label")}}
        {{form.saves(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.race.label(class="form-control-label")}}
        {{form.race(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.gender.label(class="form-control-label")}}
        {{form.gender(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.age.label(class="form-control-label")}}
        {{form.age(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.weight.label(class="form-control-label")}}
        {{form.weight(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.hair.label(class="form-control-label")}}
        {{form.hair(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.eyes.label(class="form-control-label")}}
        {{form.eyes(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.notes.label(class="form-control-label")}}
        {{form.notes(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
      </div>
      </div>

    </form>
  </div>



{% endblock %}

source/project/dungeons_and_devs/templates/index.html
{% extends "base.html" %}
{% block content %}

  <br>
  <div class="container" align='center'>
{% for charc in characters.items %}


  <div class="card font-monospace bg-dark text-light " style="width: 30rem;">
    <img src="{{ url_for('static', filename='profile_pics/default_character.png')}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h1 class="card-title font-monospace" href="">{{charc.name}}</h1>
      <p class="card-text">{{charc.notes}}</p>
      <span>
        <a href="{{ url_for('characters.character', character_id=charc.id)}}" class="btn btn-primary">View Character</a>
        <a href="{{ url_for('users.user_characters',username=charc.owner.username )}}" class="btn btn-primary">View Creator</a>
      </span>


    </div>
  </div><br>

{% endfor %}


  </div>

  


  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in characters.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if characters.page == page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>



{% endblock %}

source/project/dungeons_and_devs/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron font-monospace">
    <br>
    <h1>About Dungeons & Developers</h1>
    <p>Dungeons & Developers is an interactive web based application for D&D enthusiats. The application allows for users to create their characters within our web-portal and attatch attributes and items alike to said characters. Furthermore if you and your campaign mates use the Discord App we also provide a bot that given a set of commands can access the attributes of all your characters. This tool aims to ease the pain or pen and paper edits while trying to enjoy the game you love. </p>
  </div>

  <div class="row row-cols-1 row-cols-md-2 g-4 ">
  <div class="col "  style="width: 27rem;">
    <div class="card ">
      <img src="{{ url_for('static', filename='media/signup.png')}}" class="card-img-top" alt="...">
      <div class="card-body font-monospace bg-dark text-light">
        <h5 class="card-title">Sign Up</h5>
        <p class="card-text ">Head over to the 'Register' tab to embark on your 3.5E journey with us at Dungeons & Developers. Your email is not shared with any third party. This site is for users by users. &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</p>
      </div>
    </div>
  </div>
  <br><br>
  <div class="col "  style="width: 27rem;">
    <div class="card">
      <img src="{{ url_for('static', filename='media/create.png')}}" class="card-img-top" alt="...">
      <div class="card-body font-monospace bg-dark text-light">
        <h5 class="card-title ">Create</h5>
        <p class="card-text">Create your character by adding a backstory, items, class, and much more through our 'Create Character' tab. Coming soon: a pick list of all Standard 3.5E items, and attributes to add to your already existing character(s).</p>
      </div>
    </div>
  </div>
  <br><br>
  <div class="col"  style="width: 27rem;">
    <div class="card">
      <img src="{{ url_for('static', filename='media/conquer.png')}}" class="card-img-top" alt="...">
      <div class="card-body font-monospace bg-dark text-light">
        <h5 class="card-title">Campaign</h5>
        <p class="card-text">Find Inspiration for new characters by sifting through our database of users characters available to you on the 'Dungeons & Developers' tab above. Here you can also find like minded users and potentially a campaign to join.</p>
      </div>
    </div>
  </div>
</div>
<br><br>

{% endblock %}

source/project/dungeons_and_devs/templates/login.html
{% extends "base.html" %}
{% block content %}
  <br><br>


  <form method="POST">
    <div class="card font-monospace shadow-lg p-3 mb-5 bg-body rounded">
      <div class="card-header">
        Please Provide the Appropriate Credentials
      </div>
      <div class="card-body">
        {{form.hidden_tag()}}
        {{form.email.label(class="form-label")}}{{form.email(class="form-control")}}<br>
        {{form.password.label(class="form-label")}}{{form.password(class="form-control")}}<br>
        {{form.submit(class="btn btn-primary")}}
      </div>
    </div>
  </form>



{% endblock %}

source/project/dungeons_and_devs/templates/register.html
{% extends "base.html" %}
{% block content %}

<br><br>


<form method="POST">
  <div class="card font-monospace shadow-lg p-3 mb-5 bg-body rounded">
    <div class="card-header">
      No information provided will be shared by Dungeons & Developers
    </div>
    <div class="card-body">
      {{form.hidden_tag()}}
      {{form.email.label(class="form-label")}}{{form.email(class="form-control")}}<br>
      {{form.username.label(class="form-label")}}{{form.username(class="form-control")}}<br>
      {{form.password.label(class="form-label")}}{{form.password(class="form-control")}}<br>
      {{form.pass_confirm.label(class="form-label")}}{{form.pass_confirm(class="form-control")}}<br>
      {{form.submit(class="btn btn-primary")}}
    </div>
  </div>
</form>


{% endblock %}

source/project/dungeons_and_devs/templates/user_characters.html
{% extends "base.html" %}
{% block content %}
<br>
  <div class="container font-monospace" align='center'>
    <div class="jumbotron">
      <div align='center'>
        <h1>Welcome to the page for {{user.username}}</h1>
        <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" alt="">
        <br><br>
      </div>
    </div>


    <div class="card text-white bg-dark mb-3" style="max-width: 30rem;">
      <div class="card-header">Characters by: {{user.username}}</div>
      <div class="card-body">


{% for chara in characters.items %}

  <h5 class="card-title"><a href="{{ url_for('characters.character', character_id=chara.id)}}">{{ chara.name }}</a></h5>

  <!-- THIS  is where ALL CHARACTER INFO WILL BE DISPLAYED, NEED TO GET FANCY WITH BOOTSTRAP HERE, LOTS OF ADATA PER CHARACTER-->
{% endfor %}
      </div>
    </div>
  </div>

<!-- PAGINATION FOR CHARACTERS-->
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center font-monospace">
    {% for page_num in characters.iter_pages() %}
      {% if characters.page == page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('users.user_characters',username=user.username,page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
          <a class="page-link" href="{{url_for('users.user_characters',username=user.username,page=page_num)}}">{{page_num}}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}